### ISSUE TITLE
fails when installing to vs2012

### ISSUE THREAD

**Issue by joeldart** [akoeplinger/WiX.Toolset.NuGet#1]
```
Installing 'WiX.Toolset 3.8.1128.0'.
Successfully installed 'WiX.Toolset 3.8.1128.0'.
Adding 'WiX.Toolset 3.8.1128.0' to Installer.
Successfully added 'WiX.Toolset 3.8.1128.0' to Installer.
Executing script file '<path-to-build-with spaces> Build\packages\WiX.Toolset.3.8.1128.0\tools\Uninstall.ps1'.
Uninstalling 'WiX.Toolset 3.8.1128.0'.
Successfully uninstalled 'WiX.Toolset 3.8.1128.0'.
Install failed. Rolling back...
Object reference not set to an instance of an object.
```

**Comment by akoeplinger** [comment]
Thanks for the report, I see the same output in VS2013.

It seems to be caused by NuGet 2.8, I've confirmed that the installation works fine in NuGet 2.7.2.

As a workaround, you can downgrade NuGet to 2.7.2 (http://nuget.codeplex.com/releases/view/112815), install the package and then upgrade to 2.8 again.
I'll unlist the package until I find out how to fix the issue.

**Comment by akoeplinger** [comment]
Installation works fine again in NuGet 2.8.1 (not yet released).
It looks like this commit fixed the bug during installation, as WiX projects don't have a target framework: http://nuget.codeplex.com/SourceControl/changeset/81a60d41acf3c72e1ed9157c705e510f517c7f33
There's unfortunately nothing I can do for now as the bug lies deep within NuGet.

@jeffhandley Any estimates on when NuGet 2.8.1 is released or if there's a better solution to his problem for now?

**Comment by akoeplinger** [comment]
NuGet 2.8.1 was released yesterday with the [bug fix](http://nuget.codeplex.com/workitem/4020) for this issue.
I've relisted the WiX.Toolset packages on nuget.org, so everything should be working again :smile:
