### ISSUE TITLE
Install.ps1 script incorrectly excludes non-wixproj projects

### ISSUE THREAD

**Issue by saxonww** [akoeplinger/WiX.Toolset.NuGet#3]
I'd like to use this package for an extension project - these can be c#, c++ or vb - but the Install.ps1 script only allows restoration to WiX projects (.wixproj).

**Comment by akoeplinger** [comment]
The extension projects are normal C# class library projects, correct?
I originally put that check into place because the install scripts look for certain properties in the .wixproj, so installing it into a normal class library doesn't really make sense.

I agree that this is not ideal for extension projects, but here's a workaround:
1. Create a temporary .wixproj and install the package there
2. Copy the WiX.Toolset entry from packages.config into your extension project
3. Manually add a reference to the wix.dll in \packages\WiX.Toolset\tools\wix\ to the extension project
4. Delete the temporary .wixproj

Let me know if this works for you :)

**Comment by saxonww** [comment]
Yes, extensions can be C# class libraries. I think they can also be vcxproj and vbproj.

Your workaround is what I ended up doing. It will work as long as the WiX version is not bumped, which is probably good enough.

**Comment by akoeplinger** [comment]
Yeah, the WiX version is rarely bumped, so that shouldn't be a huge problem.

I'll see if I can make the logic smarter in one of the next releases, but for now the workaround should be sufficient.
