### ISSUE TITLE
Build server package restore

### ISSUE THREAD

**Issue by gregbty** [akoeplinger/WiX.Toolset.NuGet#4]
My build server checkouts my repository, then runs msbuild on my solution which has package restore enabled. However, when it gets to my WiX projects it complains that it can not find the wix.targets that is referenced from the installed solution packages. When I checked the packages folder for the solution, the WiX package didn't seem to have restored. Am I missing something here? Is it supposed to automatically pull down the packages during the build?

**Comment by akoeplinger** [comment]
WiX projects differ from C# projects in that they actually redefine the common MSBuild targets like `PrepareForBuild` and `CheckPrerequisites` (which the NuGet restore target hooks into) in wix2010.targets. This doesn't work of course since the file isn't there until the package is restored - catch 22.

The solution is to restore NuGet packages outside of MSBuild (i.e. by invoking nuget.exe), which is the recommended practice from the NuGet team anyway: https://docs.nuget.org/Consume/Package-Restore/Migrating-to-Automatic-Package-Restore.

**Comment by akoeplinger** [comment]
Alternatively, if you can't move away from MSBuild based restore you can try changing this in your .wixproj:

``` diff
-  <Import Project="$(WixTargetsPath)" />
+  <Import Project="$(WixTargetsPath)" Condition="Exists('$(WixTargetsPath)')"/>
```

.. and then invoking `msbuild <path to .wixproj> /t:RestorePackages` to restore the Wix package manually. After that you should be able to build the parent solution just fine.

**Comment by gregbty** [comment]
Thanks for explaining this! This works for me now.
