### ISSUE TITLE
Why are there 3 WiX.Toolset packages ?

### ISSUE THREAD

**Issue by robdalsanto** [akoeplinger/WiX.Toolset.NuGet#9]
Surely we don't need:

- [WiX.Toolset](https://github.com/akoeplinger/WiX.Toolset.NuGethttps://github.com/akoeplinger/WiX.Toolset.NuGet) (v3.9),
- [WiX.Toolset.2015](https://github.com/shana/WiX.Toolset.NuGet) (v3.10)
- [WiX.Toolset.UnofficialFork](https://github.com/jozefizso/WiX.Toolset.NuGet) (v3.11)

**Comment by jnm2** [comment]
Mainly because maintainers no longer have the energy to keep up. There are two that stay up to date: https://github.com/akoeplinger/WiX.Toolset.NuGet/issues/8#issuecomment-461468544

Ideally, @wixtoolset would take over one of these package names and publish to NuGet as part of their release process. IIRC they were interested in doing this at some point.

**Comment by akoeplinger** [comment]
WiX v4 provides official NuGet packages, see https://wixtoolset.org
